In [50]:
import nltk
import pandas as pd
import Sastrawi as stw

In [45]:
df = pd.read_excel("C:/Users/hp/OneDrive/Documents/Belajar Pemrograman/PPDM/Dataset C.xlsx")
df

      No                                            Reviews  Label
0      1  Gk usah ragu blnja d sini.realpik semua barang...      1
1      2  Nice pokonamah mantaaaafffff hehehhee .. suka ...      0
2      3  Pesen brown...yg dkirim blue...cape dech...klo...      0
3      4  Kirain besar n talinya panjang,,tp trnyta keci...      0
4      5  Tas ny udah mendarat dngn slmat tp pas d tali ...      0
..   ...                                                ...    ...
195  196  baguss bangett nyesel cuma beli 3 ajaa, kualit...      1
196  197  Pertama order disini agak kecewakan sama pelay...      0
197  198  Kesekian kalinya beli disini soalnya tidak mer...      1
198  199  Pesen warna putih yang sampe warna abu abu, ba...      0
199  200  Pengirimann sngt cepattt. .\nSellernya fast re...      1

[200 rows x 3 columns]

In [46]:
df = df.iloc[20:30, :]
df

    No                                            Reviews  Label
20  21  Pengirimannya cpt, tasnya bagus, real picture,...      1
21  22  Udah langganan dan gapernah gagal, secinta itu...      1
22  23  Baguuuuusss bgt woy. Sumph ini murh bgttttt gw...      1
23  24  Mantappp banget pengemasan cuma kurang dikasih...      1
24  25  Kualitasnya emang nggk pernah ngecewain, harga...      1
25  26  The bestt emg ga prna kecewa beli di sini♥️♥️♥...      1
26  27  Bgus bgt kek keliatan mahal wkkk pdhal cman 73...      1
27  28  Logo nya kecil padahal di fotonya agak besar g...      0
28  29  Harga dibawah 100rb dapet tas sebaguss ini 😍 b...      1
29  30  Asli sih ini cantik bangt tasnya, suka sekali ...      1

In [47]:
df.shape

(10, 3)

In [48]:
token = [nltk.word_tokenize(i) for i in df["Reviews"]]

In [49]:
token

[['Pengirimannya',
  'cpt',
  ',',
  'tasnya',
  'bagus',
  ',',
  'real',
  'picture',
  ',',
  'bahannya',
  'jg',
  'bgs',
  'kayak',
  'tas',
  'mahal',
  '.'],
 ['Udah',
  'langganan',
  'dan',
  'gapernah',
  'gagal',
  ',',
  'secinta',
  'ituuu💜💜💜💜💜💜💜💜💜💜💜'],
 ['Baguuuuusss',
  'bgt',
  'woy',
  '.',
  'Sumph',
  'ini',
  'murh',
  'bgttttt',
  'gw',
  'nemu',
  'ini',
  'prsis',
  'gini',
  'd',
  'jual',
  '200ribu',
  'ini',
  'hanya',
  '79.500',
  'kualitasnyaa',
  'melebihi',
  'ekpektasi'],
 ['Mantappp',
  'banget',
  'pengemasan',
  'cuma',
  'kurang',
  'dikasih',
  'bubblewrap',
  ',',
  'tolong',
  'dong',
  'kualitas',
  'pengemasan',
  'di',
  'tingkatkan',
  'lagi',
  ',',
  'khawatir',
  'ke',
  'gencet',
  '”',
  'soalnya',
  'kaya',
  'rada',
  'gepeng😿'],
 ['Kualitasnya',
  'emang',
  'nggk',
  'pernah',
  'ngecewain',
  ',',
  'harga',
  'murah',
  'tapi',
  'kualitas',
  'nggk',
  'murahan',
  '.',
  'Thanks',
  'seller',
  '👍'],
 ['The',
  'bestt',
  'emg',
  'ga',
  'prna',
  'kecewa',
  'beli',
  'di',
  'sini♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️🥺♥️🥺🥺🥺🥺🥺🥺🥺🥺🥺♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️♥️🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺🥺😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍'],
 ['Bgus',
  'bgt',
  'kek',
  'keliatan',
  'mahal',
  'wkkk',
  'pdhal',
  'cman',
  '73rb',
  ',',
  'good',
  'lah',
  'suka',
  'bgt😘',
  'pengiriman',
  'nya',
  'juga',
  'cpet',
  'bgt',
  'kmrin',
  'di',
  'kirim',
  'tdi',
  'dzuhur',
  'udh',
  'sampe'],
 ['Logo',
  'nya',
  'kecil',
  'padahal',
  'di',
  'fotonya',
  'agak',
  'besar',
  'gtu',
  '😭',
  'cuman',
  'oke',
  'lah',
  'bahan',
  'ny',
  'oke',
  'pengiriman',
  'nya',
  'juga',
  'oke',
  'bahan',
  'ny',
  'tebal'],
 ['Harga',
  'dibawah',
  '100rb',
  'dapet',
  'tas',
  'sebaguss',
  'ini',
  '😍',
  'baru',
  'pertama',
  'order',
  'gk',
  'kecewa',
  'wahib',
  'order',
  'lgi'],
 ['Asli',
  'sih',
  'ini',
  'cantik',
  'bangt',
  'tasnya',
  ',',
  'suka',
  'sekali',
  'mau',
  'nambah',
  'lagi',
  'bingung',
  'yang',
  'mana']]

10